// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mvc-model-sample/application/model/orm/ent/schema"
	"mvc-model-sample/application/model/orm/ent/todolist"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todolistFields := schema.Todolist{}.Fields()
	_ = todolistFields
	// todolistDescDeleteFlag is the schema descriptor for delete_flag field.
	todolistDescDeleteFlag := todolistFields[3].Descriptor()
	// todolist.DefaultDeleteFlag holds the default value on creation for the delete_flag field.
	todolist.DefaultDeleteFlag = todolistDescDeleteFlag.Default.(int)
	// todolistDescCreatedAt is the schema descriptor for created_at field.
	todolistDescCreatedAt := todolistFields[4].Descriptor()
	// todolist.DefaultCreatedAt holds the default value on creation for the created_at field.
	todolist.DefaultCreatedAt = todolistDescCreatedAt.Default.(func() time.Time)
}
