// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"mvc-model-sample/application/model/orm/ent/predicate"
	"mvc-model-sample/application/model/orm/ent/todolist"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TodolistQuery is the builder for querying Todolist entities.
type TodolistQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	inters     []Interceptor
	predicates []predicate.Todolist
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TodolistQuery builder.
func (tq *TodolistQuery) Where(ps ...predicate.Todolist) *TodolistQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *TodolistQuery) Limit(limit int) *TodolistQuery {
	tq.limit = &limit
	return tq
}

// Offset to start from.
func (tq *TodolistQuery) Offset(offset int) *TodolistQuery {
	tq.offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TodolistQuery) Unique(unique bool) *TodolistQuery {
	tq.unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *TodolistQuery) Order(o ...OrderFunc) *TodolistQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// First returns the first Todolist entity from the query.
// Returns a *NotFoundError when no Todolist was found.
func (tq *TodolistQuery) First(ctx context.Context) (*Todolist, error) {
	nodes, err := tq.Limit(1).All(newQueryContext(ctx, TypeTodolist, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{todolist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TodolistQuery) FirstX(ctx context.Context) *Todolist {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Todolist ID from the query.
// Returns a *NotFoundError when no Todolist ID was found.
func (tq *TodolistQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(1).IDs(newQueryContext(ctx, TypeTodolist, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{todolist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TodolistQuery) FirstIDX(ctx context.Context) int {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Todolist entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Todolist entity is found.
// Returns a *NotFoundError when no Todolist entities are found.
func (tq *TodolistQuery) Only(ctx context.Context) (*Todolist, error) {
	nodes, err := tq.Limit(2).All(newQueryContext(ctx, TypeTodolist, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{todolist.Label}
	default:
		return nil, &NotSingularError{todolist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TodolistQuery) OnlyX(ctx context.Context) *Todolist {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Todolist ID in the query.
// Returns a *NotSingularError when more than one Todolist ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TodolistQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(2).IDs(newQueryContext(ctx, TypeTodolist, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{todolist.Label}
	default:
		err = &NotSingularError{todolist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TodolistQuery) OnlyIDX(ctx context.Context) int {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Todolists.
func (tq *TodolistQuery) All(ctx context.Context) ([]*Todolist, error) {
	ctx = newQueryContext(ctx, TypeTodolist, "All")
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Todolist, *TodolistQuery]()
	return withInterceptors[[]*Todolist](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *TodolistQuery) AllX(ctx context.Context) []*Todolist {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Todolist IDs.
func (tq *TodolistQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = newQueryContext(ctx, TypeTodolist, "IDs")
	if err := tq.Select(todolist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TodolistQuery) IDsX(ctx context.Context) []int {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TodolistQuery) Count(ctx context.Context) (int, error) {
	ctx = newQueryContext(ctx, TypeTodolist, "Count")
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*TodolistQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TodolistQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TodolistQuery) Exist(ctx context.Context) (bool, error) {
	ctx = newQueryContext(ctx, TypeTodolist, "Exist")
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TodolistQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TodolistQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TodolistQuery) Clone() *TodolistQuery {
	if tq == nil {
		return nil
	}
	return &TodolistQuery{
		config:     tq.config,
		limit:      tq.limit,
		offset:     tq.offset,
		order:      append([]OrderFunc{}, tq.order...),
		inters:     append([]Interceptor{}, tq.inters...),
		predicates: append([]predicate.Todolist{}, tq.predicates...),
		// clone intermediate query.
		sql:    tq.sql.Clone(),
		path:   tq.path,
		unique: tq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Todolist.Query().
//		GroupBy(todolist.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *TodolistQuery) GroupBy(field string, fields ...string) *TodolistGroupBy {
	tq.fields = append([]string{field}, fields...)
	grbuild := &TodolistGroupBy{build: tq}
	grbuild.flds = &tq.fields
	grbuild.label = todolist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Todolist.Query().
//		Select(todolist.FieldTitle).
//		Scan(ctx, &v)
func (tq *TodolistQuery) Select(fields ...string) *TodolistSelect {
	tq.fields = append(tq.fields, fields...)
	sbuild := &TodolistSelect{TodolistQuery: tq}
	sbuild.label = todolist.Label
	sbuild.flds, sbuild.scan = &tq.fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TodolistSelect configured with the given aggregations.
func (tq *TodolistQuery) Aggregate(fns ...AggregateFunc) *TodolistSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *TodolistQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.fields {
		if !todolist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TodolistQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Todolist, error) {
	var (
		nodes = []*Todolist{}
		_spec = tq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Todolist).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Todolist{config: tq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tq *TodolistQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	_spec.Node.Columns = tq.fields
	if len(tq.fields) > 0 {
		_spec.Unique = tq.unique != nil && *tq.unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TodolistQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   todolist.Table,
			Columns: todolist.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: todolist.FieldID,
			},
		},
		From:   tq.sql,
		Unique: true,
	}
	if unique := tq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todolist.FieldID)
		for i := range fields {
			if fields[i] != todolist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TodolistQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(todolist.Table)
	columns := tq.fields
	if len(columns) == 0 {
		columns = todolist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.unique != nil && *tq.unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TodolistGroupBy is the group-by builder for Todolist entities.
type TodolistGroupBy struct {
	selector
	build *TodolistQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TodolistGroupBy) Aggregate(fns ...AggregateFunc) *TodolistGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *TodolistGroupBy) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeTodolist, "GroupBy")
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TodolistQuery, *TodolistGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *TodolistGroupBy) sqlScan(ctx context.Context, root *TodolistQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TodolistSelect is the builder for selecting fields of Todolist entities.
type TodolistSelect struct {
	*TodolistQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *TodolistSelect) Aggregate(fns ...AggregateFunc) *TodolistSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TodolistSelect) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeTodolist, "Select")
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TodolistQuery, *TodolistSelect](ctx, ts.TodolistQuery, ts, ts.inters, v)
}

func (ts *TodolistSelect) sqlScan(ctx context.Context, root *TodolistQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
