// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"learn-gin-mvc/application/model/orm/ent/predicate"
	"learn-gin-mvc/application/model/orm/ent/todolist"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TodolistDelete is the builder for deleting a Todolist entity.
type TodolistDelete struct {
	config
	hooks    []Hook
	mutation *TodolistMutation
}

// Where appends a list predicates to the TodolistDelete builder.
func (td *TodolistDelete) Where(ps ...predicate.Todolist) *TodolistDelete {
	td.mutation.Where(ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *TodolistDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, TodolistMutation](ctx, td.sqlExec, td.mutation, td.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *TodolistDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *TodolistDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: todolist.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: todolist.FieldID,
			},
		},
	}
	if ps := td.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, td.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	td.mutation.done = true
	return affected, err
}

// TodolistDeleteOne is the builder for deleting a single Todolist entity.
type TodolistDeleteOne struct {
	td *TodolistDelete
}

// Exec executes the deletion query.
func (tdo *TodolistDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{todolist.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *TodolistDeleteOne) ExecX(ctx context.Context) {
	tdo.td.ExecX(ctx)
}
